version: '{build}'
os: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: aKioN0ffdE4bl8U2pyazFCwZeMIA7hcO8cFCRujFjhwJuvW93AOpPj5WPc+WxdF/
branches:
  only:
    - master
install:
- ps: nuget update -self
build_script:
- ps: ./Build.ps1
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    appveyor_repo_tag: true